#!/bin/sh
set -e
case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop wifi-hotspot-daemon.service >/dev/null || true
        fi
        ;;
esac
